# Generated by Django 5.1 on 2024-11-21 02:06

import mdeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dogmatics", "0003_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="preprint",
            name="abstract",
            field=mdeditor.fields.MDTextField(null=True),
        ),
    ]
