# Generated by Django 5.1 on 2024-11-16 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0003_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="verse",
            name="image",
            field=models.ImageField(null=True, upload_to="img/wordcloud"),
        ),
    ]
