# Generated by Django 5.1 on 2024-11-16 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0004_verse_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="guest_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="message_owner",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="verse",
            name="image",
            field=models.ImageField(null=True, upload_to="img/wordcloud/"),
        ),
    ]
